[workspace]
resolver = "2"
members = [
    "crates/curtana-infers",
    "crates/curtana-reads",
    "crates/curtana-knows",
]

# Common configuration properties that
# can be inherited by workspace members.
[workspace.package]
edition = "2024"
repository = "https://github.com/withcaer/curtana"
license = "FSL-1.1-MIT"
authors = [
    "With Caer, LLC <with@caer.cc>",
]

[workspace.dependencies]
curtana-infers = { path = "crates/curtana-infers" }
curtana-reads = { path = "crates/curtana-reads" }
curtana-knows = { path = "crates/curtana-knows" }
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }

[profile.dev]
# Use release optimizations during testing to
# speed up ML-based tests.
opt-level = 3
