# cargo release configuration
# Sse: https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

allow-branch = ["main"]

pre-release-commit-message = "ops: release"
tag-message = "ops: release {{crate_name}} version {{version}}"

verify = false

pre-release-hook = ["git", "cliff", "--config", "../ops/git-cliff.toml", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]